# --------------------------------------------------------------------------
# THIS FILE IS AUTOGENERATED - DO NOT EDIT MANUALLY
#
# Source: Containerfile.j2
# --------------------------------------------------------------------------

# syntax=docker/dockerfile:1
ARG BASE_VERSION=15
FROM ghcr.io/daemonless/base:${BASE_VERSION}

ARG FREEBSD_ARCH=amd64
ARG PACKAGES="openjdk21 ca_root_nss jq"
ARG UPSTREAM_URL="https://api.github.com/repos/Stirling-Tools/Stirling-PDF/releases/latest"
ARG UPSTREAM_JQ=".tag_name"
ARG HEALTHCHECK_ENDPOINT="http://localhost:8080/"

ENV HEALTHCHECK_URL="${HEALTHCHECK_ENDPOINT}"

LABEL org.opencontainers.image.title="Stirling-PDF" \
      org.opencontainers.image.description="Locally hosted web application for performing various operations on PDF files — merge, split, compress, convert, OCR, and more." \
      org.opencontainers.image.source="https://github.com/daemonless/stirling-pdf" \
      org.opencontainers.image.url="https://www.stirlingpdf.com/" \
      org.opencontainers.image.licenses="MIT" \
      org.opencontainers.image.vendor="daemonless" \
      org.opencontainers.image.authors="daemonless" \
      io.daemonless.category="Utilities" \
      io.daemonless.port="8080" \
      io.daemonless.volumes="/config" \
      io.daemonless.arch="${FREEBSD_ARCH}" \
      io.daemonless.upstream-url="${UPSTREAM_URL}" \
      io.daemonless.upstream-jq="${UPSTREAM_JQ}" \
      io.daemonless.healthcheck-url="${HEALTHCHECK_ENDPOINT}" \
      io.daemonless.packages="${PACKAGES}"

# Install Java runtime
RUN pkg update && \
    pkg install -y ${PACKAGES} && \
    pkg clean -ay && \
    rm -rf /var/cache/pkg/* /var/db/pkg/repos/*

# Download Stirling-PDF JAR
RUN --mount=type=secret,id=github_token \
    GITHUB_TOKEN=$(cat /run/secrets/github_token 2>/dev/null || echo "") && \
    if [ -n "${GITHUB_TOKEN}" ]; then \
      printf 'machine api.github.com login x-access-token password %s\nmachine github.com login x-access-token password %s\n' \
        "${GITHUB_TOKEN}" "${GITHUB_TOKEN}" > /root/.netrc && \
      chmod 600 /root/.netrc; \
    fi && \
    VERSION=$(fetch -qo - "https://api.github.com/repos/Stirling-Tools/Stirling-PDF/releases/latest" | jq -r '.tag_name') && \
    echo "Installing Stirling-PDF ${VERSION}" && \
    mkdir -p /app && \
    fetch -qo /app/Stirling-PDF.jar \
        "https://github.com/Stirling-Tools/Stirling-PDF/releases/download/${VERSION}/Stirling-PDF.jar" && \
    echo "${VERSION#v}" > /app/version && \
    chown -R bsd:bsd /app && \
    rm -f /root/.netrc

RUN mkdir -p /config && chown -R bsd:bsd /config

# Copy root filesystem
COPY root/ /

# Set permissions
RUN chmod +x /etc/services.d/stirling-pdf/run /healthz /etc/cont-init.d/* 2>/dev/null || true

# --- Expose (Injected by Generator) ---
EXPOSE 8080

# --- Volumes (Injected by Generator) ---
VOLUME /config